CCFLAGS = -lncurses
CC = gcc

SOURCES_SERVER = Server.c
OBJECTS_SERVER = $(SOURCES_SERVER:.c=.o)
EXECUTABLE_SERVER = $(SOURCES_SERVER:.c=)

SOURCES_CLIENT = Client.c
OBJECTS_CLIENT = $(SOURCES_CLIENT:.c=.o)
EXECUTABLE_CLIENT = $(SOURCES_CLIENT:.c=)

LIB_GRAPH_DIR = graph/
LIB_GRAPH = $(LIB_GRAPH_DIR:/=)

all: $(EXECUTABLE_CLIENT) $(EXECUTABLE_SERVER)

debug: CCFLAGS += -g
#debug: CCFLAGS += -DDEBUG
debug: clean
debug: all

$(EXECUTABLE_SERVER): $(OBJECTS_SERVER)
	$(CC) $(OBJECTS_SERVER) -o $(EXECUTABLE_SERVER).elf

$(EXECUTABLE_CLIENT): libgraph $(OBJECTS_CLIENT)
	$(CC) $(OBJECTS_CLIENT) -o $(EXECUTABLE_CLIENT).elf $(CCFLAGS) -L./$(LIB_GRAPH) -l$(LIB_GRAPH)

libgraph:
	make -C $(LIB_GRAPH_DIR)

$(OBJECTS_CLIENT): $(SOURCES_CLIENT)
	$(CC) $(SOURCES_CLIENT) -c $(CCFLAGS)

$(OBJECTS_SERVER): $(SOURCES_SERVER)
	$(CC) $(SOURCES_SERVER) -c

.PHONY: clean
clean:
	rm *.elf *.o
